---
Name: ProductQuestionMain
---
Product:
  extensions:
    - ProductQuestion_ProductDecorator

Product_Controller:
  extensions:
    - ProductQuestion_ProductControllerDecorator

Order:
  extensions:
    - ProductQuestion_OrderExtension

OrderItem:
  extensions:
    - ProductQuestion_OrderItemExtension

ProductQuestion:
  number_per_row: 1

ProductConfigModelAdmin:
  managed_models:
    - ProductQuestion


---
Only:
  classexists: 'ProductVariation'
---
ProductVariation:
  extensions:
    - ProductQuestion_ProductVariationDecorator
